# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: raspbilly_dev
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql
  database: raspbilly_test
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  database: raspbilly_production
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
